runtime: go118
env_variables:
  INSTANCE_UNIX_SOCKET: 34.84.51.52
  DB_USER: admin
  DB_PASS: 345y5h0p#011022
  DB_NAME: easyshop-db
  APP_PORT: 8080
  MODE: PROD
  FIREBASE_AUTH_KEY: "BPEUDC9XFKTasZ7XLocVf1WXAg_SYRizlCDpHQ0Mvu2JeQwn4Wx9vi6RrN4nWlay_I_VIU-E1CUe1QWZ7qXuEPU"
  ADMIN_EMAIL: tokyo@easyshop-jp.com