UPDATE status SET idx = 1, name = 'Waiting Verification' WHERE code = 'W';
UPDATE status SET idx = 2 WHERE code = 'R';
UPDATE status SET idx = 3 WHERE code = 'A';
UPDATE status SET idx = 4 WHERE code = 'C';
UPDATE status SET idx = 5 WHERE code = 'PW';
UPDATE status SET idx = 6 WHERE code = 'PR';
UPDATE status SET idx = 7 WHERE code = 'PA';
UPDATE status SET idx = 8 WHERE code = 'IP';
UPDATE status SET idx = 9 WHERE code = 'IC';
UPDATE status SET idx = 10 WHERE code = 'IR';
UPDATE status SET idx = 11 WHERE code = 'IS';